web_visualize/visualize/urls.py
from django.urls import path
from . import views

app_name = 'visualize'
urlpatterns = [
    path('', views.index, name="index"),
    path('view/<label_group>', views.view_images, name="view"),
    path('search',views.search, name="search")
]

web_visualize/web_visualize/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('visualize.urls'))
]

web_visualize/visualize/models.py
from django.db import models

# Create your models here.

web_visualize/visualize/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from . import util

# Create your views here.

def index(request):
    list_label = util.list_label_group()
    return render(request, 'visualize/index.html', {
        "list_label": list_label
    })

def view_images(request, label_group):
    label_group = int(label_group)
    list_image_paths, list_titles = util.information_retrieval(label_group)
    return render(request, 'visualize/views.html', {
        "list_image_paths": list_image_paths,
        "list_titles": list_titles
    })

def search(request):
    label = request.POST.get('label').strip()
    label = int(label)
    labels_founded = util.search_by_label(str(label))
    return render(request, "visualize/search.html", {
        "labels_founded": labels_founded
    })

web_visualize/visualize/templates/visualize/index.html
{% extends 'visualize/layout.html' %}

{% block main %}
    <!-- <ul>
        {% for label in list_label %}
            <a href="{% url 'visualize:view' label %}">
                <li>{{ label }}</li>
            </a>
        {% endfor %}
    </ul> -->
{% endblock %}

web_visualize/visualize/templates/visualize/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Visualize</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'visualize/styles.css' %}">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <label>Search</label>
                <form action="{% url 'visualize:search' %}" method="POST">
                    {% csrf_token %}
                    <input class="form_control" type="text" name="label" placeholder="Search by label">
                </form>
                <form>
                    <input class="form_control" type="text" name="keyword" placeholder="Search by keyword">
                </form>
                <a href="{% url 'visualize:index' %}">Home Page</a><br>
                <a href="">Random Page</a>
            </div>
            <div class="maincontent col-lg-10 col-md-9">
                {% block main %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>

web_visualize/visualize/templates/visualize/search.html
{% extends 'visualize/layout.html' %}

{% block main %}
    <ul>
        {% for label in labels_founded %}
            <li>
                <a href="{% url 'visualize:view' label %}">
                    {{ label }}
                </a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

web_visualize/visualize/templates/visualize/views.html
{% extends 'visualize/layout.html' %}

{% load static %}

{% block main %}
    <ul>
        {% for title in list_titles %}
            <li>{{ title }}</li>
        {% endfor %}
    </ul>
    {% for image_path in list_image_paths %} 
            <img style="width: auto; height: auto;" src="{% get_static_prefix %}images/{{image_path}}">
    {% endfor %}
{% endblock %}